### ISSUE TITLE
Unable to load on 1.21.3

### ISSUE THREAD

**Issue by jhqwqmc** [Non0reo/ImgToShader#4]
```log
[00:00:44] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_gui_overlay (VertexFormat[Position, Color]): Could not find shader: minecraft:rendertype_gui_overlay (VERTEX)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at awb.a(SourceFile:68) ~[1.21.3.jar:?]
	at bry.d(SourceFile:164) ~[1.21.3.jar:?]
	at bsc.d(SourceFile:23) ~[1.21.3.jar:?]
	at bry.B(SourceFile:138) ~[1.21.3.jar:?]
	at bry.bA(SourceFile:123) ~[1.21.3.jar:?]
	at fmg.c(SourceFile:1307) [1.21.3.jar:?]
	at fmg.f(SourceFile:933) [1.21.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [1.21.3.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) [JavaWrapper.jar:?]
Caused by: java.lang.RuntimeException: Failed to load required shader programs:
 - minecraft:core/rendertype_gui_overlay (VertexFormat[Position, Color]): Could not find shader: minecraft:rendertype_gui_overlay (VERTEX)
	at gmc.a(SourceFile:174) ~[1.21.3.jar:?]
	at gmc.a(SourceFile:37) ~[1.21.3.jar:?]
	at awa.a(SourceFile:14) ~[1.21.3.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 13 more
```

**Comment by vancorl** [comment]
:(

**Comment by WinterBear** [comment]
You can work around this by editing the generated file `rendertype_gui_overlay.json` and putting `core/` in front of the vertex & fragment parameters.
```
    "vertex": "core/rendertype_gui_overlay",
    "fragment": "core/rendertype_gui_overlay",
```

Note there still seems to be some issues with the tool, loading bar color doesn't seem to work right
